classdef WelchSpectrumAnalyzer
% WELCHSPECTRUMANALYZER Computes Welch spectra
%
%   This class allows to set up the analysis ones and compute spectra with
%   the same parameters afterwards. It does not implement any computation
%   itself relying instead on the WELCHSPECTRUM class.
%
%   See also: WELCHSPECTRUM, WELCHSPECTRUMPLOTTER

    properties(GetAccess = public, SetAccess = public)
        % Structure with named parameters, passed into WelchSpectrum.of()
        params
    end

    methods(Access = public)
        % Compute Welch spectrum of signals
        varargout = do(this, sig);
    end

    methods(Access = public)
        % The constructor just stores the parameters
        function this = WelchSpectrumAnalyzer(options)
            arguments(Input)
                options.SegmentLenght ...
                    {mustBePositive} = ...
                    [];
                options.SegmentLenghtMode ...
                    {mustBeMember(options.SegmentLenghtMode, ...
                        ["Relative", "Absolute"])} = ...
                    "Relative";

                options.Overlap (1,1) ...
                    {mustBeInRange(options.Overlap, ...
                        0, 1, "exclude-upper")} = ...
                    0.5;

                options.PowTraceFunction ...
                    {mustBeMember(options.PowTraceFunction, ...
                        ["Average", "MaxHold", "MinHold"])} = ...
                    "Average";
                options.PhsTraceFunction ...
                    {mustBeMember(options.PhsTraceFunction, ...
                        ["Average", "MaxHold", "MinHold"])} = ...
                    "Average";

                % chebwin, gausswin, kaiser, and tukeywin require a
                % parameter. One must create them manually and pass as
                % custom.
                options.Window ...
                    {mustBeMember(options.Window, ...
                        ["barthannwin" "bartlett" "blackman" ...
                        "blackmanharris" "bohmanwin" "flattopwin" ...
                        "hamming" "hann" "nuttallwin" "parzenwin" ...
                        "rectwin" "triang" "custom"])} = ...
                    "hann";
                options.CustomWindow function_handle = ...
                    @(p) assert(0);
            end

            this.params = options;
        end
    end

end
