function varargout = of(sigs, options)
% OF Compute Welch spectra of Signals
%
%   [SP1, ..., SPN] = WELCHSPECTRUM.OF(SIG1, ..., SIGN, NAMEARGS) computes
%   Welch spectra for SIG1, ..., SIGN signals using the named arguments
%   NAMEARGS and returns them as WELCHSPECTRUM objects SP1, ..., SPN.
%   See "arguments" block for further details on the named arguments.

arguments(Input, Repeating)
    sigs (1,1) Signal {mustBeNonmissing}
end

arguments(Input)
    options.SegmentLenght (1,1) ...
        {mustBePositive} = ...
        0.5;
    options.SegmentLenghtMode ...
        {mustBeMember(options.SegmentLenghtMode, ...
            ["Relative", "Absolute"])} = ...
        "Relative";

    options.Overlap (1,1) ...
        {mustBeInRange(options.Overlap, 0, 1, "exclude-upper")} = ...
        0.5;

    options.PowTraceFunction ...
        {mustBeMember(options.PowTraceFunction, ...
            ["Average", "MaxHold", "MinHold"])} = ...
        "Average";
    options.PhsTraceFunction ...
        {mustBeMember(options.PhsTraceFunction, ...
            ["Average", "MaxHold", "MinHold"])} = ...
        "Average";
    
    % chebwin, gausswin, kaiser, and tukeywin require a parameter. One 
    % must create them manually and pass as custom.
    options.Window ...
        {mustBeMember(options.Window, ...
            ["barthannwin" "bartlett" "blackman" "blackmanharris" ...
            "bohmanwin" "flattopwin" "hamming" "hann" "nuttallwin" ...
            "parzenwin" "rectwin" "triang" "custom"])} = ...
        "hann";
    options.CustomWindow function_handle = ...
        @(p) assert(0);
end

arguments(Output, Repeating)
    varargout (1,1) WelchSpectrum
end

assert(nargout <= nargin, ...
    "WelchSpectrum:of:tooManyOutputArguments", ...
    "The number of output arguments must not " + ...
    "exceed the number of input ones.");

for i = nargout:-1:1
    varargout{i} = WelchSpectrum(sigs{i}, options);
end

end
