function mustBeAxisLimits(A)
% MUSTBEAXISLIMITS Validate that input defines axis limits
%
%   MUSTBEAXISLIMITS(A) throws an error if A is not "auto" a 2-element
%   vector of increasing numeric values.


if (ischar(A) && isrow(A)) || (isstring(A) && isscalar(A))
    if ~strcmp(A, "auto")
        throwAsCaller(MException( ...
            "AVS:validators:mustBeAxisLimits", ...
            "A value must be 'auto' or " + ...
            "a 2-element vector of increasing numeric values." ...
        ));
    end
else
    if ~isnumeric(A) && ~islogical(A)
        throwAsCaller(MException( ...
            "AVS:validators:mustBeNumericOrLogical", ...
            "Value must be numeric or logical."));
    end
    
    if ~isreal(A)
        throwAsCaller(MException( ...
            "AVS:validators:mustBeReal", ...
            "Value must be real."));
    end

    if ~isvector(A)
        throwAsCaller(MException( ...
            "AVS:validators:mustBeVector", ...
            "Value must be a 1-by-n vector or an n-by-1 vector."));
    end

    if ~(length(A) == 2) || ~(A(1) < A(2))
        throwAsCaller(MException( ...
            "AVS:validators:mustBeAxisLimits", ...
            "A value must be 'auto' or " + ...
            "a 2-element vector of increasing numeric values." ...
        ));
    end
end

end
